services:
  - type: web
    name: quantioco-server
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        value: quantioco_super_secret_jwt_key_2024
      - key: CLIENT_URL
        value: https://client-ten-mu-84.vercel.app
